//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZigmaWeb.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZigmaWeb.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درباره من.
        /// </summary>
        public static string AboutMe {
            get {
                return ResourceManager.GetString("AboutMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درباره وبلاگ.
        /// </summary>
        public static string AboutWeblog {
            get {
                return ResourceManager.GetString("AboutWeblog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسترسی به شبکه علمی.
        /// </summary>
        public static string AccessToNetwork {
            get {
                return ResourceManager.GetString("AccessToNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لینک فعال سازی حساب کاربری شما منقضی شده است. لطفا به صفحه ارسال لینک فعال سازی مراجعه کنید و آدرس پست الکترونیک خود را وارد کنید تا مجددا برای شما لینک فعال سازی ارسال شود..
        /// </summary>
        public static string AccountActivationLinkHasExpired {
            get {
                return ResourceManager.GetString("AccountActivationLinkHasExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عضویت شما در زیگماوب تایید شد..
        /// </summary>
        public static string AccountVerfied {
            get {
                return ResourceManager.GetString("AccountVerfied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عربی.
        /// </summary>
        public static string Arabic {
            get {
                return ResourceManager.GetString("Arabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ تولد.
        /// </summary>
        public static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس وبلاگ *.
        /// </summary>
        public static string BlogAddressWithStar {
            get {
                return ResourceManager.GetString("BlogAddressWithStar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to از این نام نمی توانید استفاده کنید. لطفا نام دیگری انتخاب کنید..
        /// </summary>
        public static string BlogNameIsNotAvailable {
            get {
                return ResourceManager.GetString("BlogNameIsNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان وبلاگ *.
        /// </summary>
        public static string BlogTitleWithStar {
            get {
                return ResourceManager.GetString("BlogTitleWithStar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متن تبلیغات.
        /// </summary>
        public static string BusinessIntroduceText {
            get {
                return ResourceManager.GetString("BusinessIntroduceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لغو.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مطالب برگزیده.
        /// </summary>
        public static string ChosenContent {
            get {
                return ResourceManager.GetString("ChosenContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دیدگاه.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دیدگاه دیگران.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تایید شده.
        /// </summary>
        public static string Confirmed {
            get {
                return ResourceManager.GetString("Confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تکرار کلمه عبور.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تماس با ما.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در زیگماوب شما می توانید مطالب و مقالات خود را در زمینه های مختلف نگارش کرده یا از منابع دیگر ترجمه کنید و از طریق موتورهای جستجو با میلیون ها کاربر در سرتاسر دنیا به اشتراک بگذارید.
        /// </summary>
        public static string Content_AboutZigmaWeb {
            get {
                return ResourceManager.GetString("Content_AboutZigmaWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما می توانید با نویسندگان و مطالب آنان در یک شبکه علمی آشنا شوید و به آنان جهت بهبود مطالبشان بازخورد بدهید.
        /// </summary>
        public static string Content_AccessToNetwork {
            get {
                return ResourceManager.GetString("Content_AccessToNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پربازدیدترین مطالب ماه.
        /// </summary>
        public static string Content_PopularContent {
            get {
                return ResourceManager.GetString("Content_PopularContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مطالب خود را به اشتراک بگذارید.
        /// </summary>
        public static string Content_Slogan {
            get {
                return ResourceManager.GetString("Content_Slogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نویسندگان برتر زیگماوب.
        /// </summary>
        public static string Content_TopAuthors {
            get {
                return ResourceManager.GetString("Content_TopAuthors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما می توانید مطالب و مقالات مفید را از یک زبان به زبان های دیگر ترجمه کنید.
        /// </summary>
        public static string Content_Translation {
            get {
                return ResourceManager.GetString("Content_Translation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما می توانید مطالب و مقالات خود در زمینه های مختلف نگارش درآورید.
        /// </summary>
        public static string Content_Writing {
            get {
                return ResourceManager.GetString("Content_Writing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان مطلب.
        /// </summary>
        public static string ContentTitle {
            get {
                return ResourceManager.GetString("ContentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایجاد.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایجاد حساب.
        /// </summary>
        public static string CreateAccount {
            get {
                return ResourceManager.GetString("CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عربی.
        /// </summary>
        public static string Culture_ar_AE {
            get {
                return ResourceManager.GetString("Culture_ar_AE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آذری.
        /// </summary>
        public static string Culture_az_Latn_AZ {
            get {
                return ResourceManager.GetString("Culture_az_Latn_AZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آلمانی.
        /// </summary>
        public static string Culture_de_DE {
            get {
                return ResourceManager.GetString("Culture_de_DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انگلیسی.
        /// </summary>
        public static string Culture_en_US {
            get {
                return ResourceManager.GetString("Culture_en_US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسپانیایی.
        /// </summary>
        public static string Culture_es_ES {
            get {
                return ResourceManager.GetString("Culture_es_ES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فارسی.
        /// </summary>
        public static string Culture_fa_IR {
            get {
                return ResourceManager.GetString("Culture_fa_IR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرانسوی.
        /// </summary>
        public static string Culture_fr_FR {
            get {
                return ResourceManager.GetString("Culture_fr_FR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایتالیایی.
        /// </summary>
        public static string Culture_it_IT {
            get {
                return ResourceManager.GetString("Culture_it_IT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ژاپنی.
        /// </summary>
        public static string Culture_ja_JP {
            get {
                return ResourceManager.GetString("Culture_ja_JP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ترکی.
        /// </summary>
        public static string Culture_tr_TR {
            get {
                return ResourceManager.GetString("Culture_tr_TR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چینی.
        /// </summary>
        public static string Culture_zh_CN {
            get {
                return ResourceManager.GetString("Culture_zh_CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلمه عبور فعلی.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فروردین.
        /// </summary>
        public static string Date_Month1 {
            get {
                return ResourceManager.GetString("Date_Month1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دی.
        /// </summary>
        public static string Date_Month10 {
            get {
                return ResourceManager.GetString("Date_Month10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بهمن.
        /// </summary>
        public static string Date_Month11 {
            get {
                return ResourceManager.GetString("Date_Month11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسفند.
        /// </summary>
        public static string Date_Month12 {
            get {
                return ResourceManager.GetString("Date_Month12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اردیبهشت.
        /// </summary>
        public static string Date_Month2 {
            get {
                return ResourceManager.GetString("Date_Month2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خرداد.
        /// </summary>
        public static string Date_Month3 {
            get {
                return ResourceManager.GetString("Date_Month3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تیر.
        /// </summary>
        public static string Date_Month4 {
            get {
                return ResourceManager.GetString("Date_Month4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرداد.
        /// </summary>
        public static string Date_Month5 {
            get {
                return ResourceManager.GetString("Date_Month5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شهریور.
        /// </summary>
        public static string Date_Month6 {
            get {
                return ResourceManager.GetString("Date_Month6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مهر.
        /// </summary>
        public static string Date_Month7 {
            get {
                return ResourceManager.GetString("Date_Month7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آبان.
        /// </summary>
        public static string Date_Month8 {
            get {
                return ResourceManager.GetString("Date_Month8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آذر.
        /// </summary>
        public static string Date_Month9 {
            get {
                return ResourceManager.GetString("Date_Month9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش پروفایل.
        /// </summary>
        public static string EditProfile {
            get {
                return ResourceManager.GetString("EditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام موسسه آموزشی.
        /// </summary>
        public static string EducationalOrganizationName {
            get {
                return ResourceManager.GetString("EducationalOrganizationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقطع تحصیلی.
        /// </summary>
        public static string EducationGrade {
            get {
                return ResourceManager.GetString("EducationGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاردانی.
        /// </summary>
        public static string EducationGrade_Associate {
            get {
                return ResourceManager.GetString("EducationGrade_Associate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کارشناسی.
        /// </summary>
        public static string EducationGrade_Bachelor {
            get {
                return ResourceManager.GetString("EducationGrade_Bachelor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دبیرستان / هنرستان.
        /// </summary>
        public static string EducationGrade_HighSchool {
            get {
                return ResourceManager.GetString("EducationGrade_HighSchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دیپلم.
        /// </summary>
        public static string EducationGrade_HighSchoolDiploma {
            get {
                return ResourceManager.GetString("EducationGrade_HighSchoolDiploma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کارشناسی ارشد.
        /// </summary>
        public static string EducationGrade_Master {
            get {
                return ResourceManager.GetString("EducationGrade_Master", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دکترا.
        /// </summary>
        public static string EducationGrade_Phd {
            get {
                return ResourceManager.GetString("EducationGrade_Phd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پست الکترونیک.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سال پایان.
        /// </summary>
        public static string EndYear {
            get {
                return ResourceManager.GetString("EndYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس فیسبوک.
        /// </summary>
        public static string FacebookUrl {
            get {
                return ResourceManager.GetString("FacebookUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زن.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت کلمه عبور.
        /// </summary>
        public static string ForgotYourPassword {
            get {
                return ResourceManager.GetString("ForgotYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جمعه.
        /// </summary>
        public static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جنسیت.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نامعتبر.
        /// </summary>
        public static string Invalid {
            get {
                return ResourceManager.GetString("Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات مربوط به فعال سازی حساب کاربری نامعتبر است..
        /// </summary>
        public static string InvalidAccountActivationInfo {
            get {
                return ResourceManager.GetString("InvalidAccountActivationInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس وبلاگ تنها از حروف انگلیسی تشکیل می شود و باید حداقل 4 حرف و حداکثر 20 حرف باشد. استفاده از اعداد، علامت‌ها یا خط فاصله مجاز نیست..
        /// </summary>
        public static string InvalidBlogName {
            get {
                return ResourceManager.GetString("InvalidBlogName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلمه عبور فعلی اشتباه است.
        /// </summary>
        public static string InvalidCurrentPassword {
            get {
                return ResourceManager.GetString("InvalidCurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پست الکترونیک نامعتبر است.
        /// </summary>
        public static string InvalidEmailAddress {
            get {
                return ResourceManager.GetString("InvalidEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس نامعتبر است.
        /// </summary>
        public static string InvalidUrl {
            get {
                return ResourceManager.GetString("InvalidUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری و یا کلمه عبور اشتباه است.
        /// </summary>
        public static string InvalidUsernameOrPassword {
            get {
                return ResourceManager.GetString("InvalidUsernameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان شغلی.
        /// </summary>
        public static string JobName {
            get {
                return ResourceManager.GetString("JobName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زبان.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ آخرین ورود.
        /// </summary>
        public static string LastLoginDate {
            get {
                return ResourceManager.GetString("LastLoginDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام خانوادگی.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس لینکدین.
        /// </summary>
        public static string LinkedInUrl {
            get {
                return ResourceManager.GetString("LinkedInUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صفحه ورود.
        /// </summary>
        public static string LoginPage {
            get {
                return ResourceManager.GetString("LoginPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرد.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرد.
        /// </summary>
        public static string Man {
            get {
                return ResourceManager.GetString("Man", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meta Description.
        /// </summary>
        public static string MetaDescription {
            get {
                return ResourceManager.GetString("MetaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meta Keywords.
        /// </summary>
        public static string MetaKeywords {
            get {
                return ResourceManager.GetString("MetaKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره موبایل.
        /// </summary>
        public static string MobileNumber {
            get {
                return ResourceManager.GetString("MobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دوشنبه.
        /// </summary>
        public static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد تایید  ارسال شده منقضی شده است، برای ارسال مجدد کد تایید روی دکمه ی زیر کلیک کنید..
        /// </summary>
        public static string MsgConfirmCodeExpired {
            get {
                return ResourceManager.GetString("MsgConfirmCodeExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پست الکترونیکی که وارد کرده‌اید قابل استفاده نیست. لطفا از یک پست الکترونیک دیگر استفاده کنید.
        /// </summary>
        public static string MsgEmailAddressIsAlreadyRegistered {
            get {
                return ResourceManager.GetString("MsgEmailAddressIsAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هنگام پردازش اطلاعات خطا رخ داد.
        /// </summary>
        public static string MsgGeneralError {
            get {
                return ResourceManager.GetString("MsgGeneralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ابعاد تصویر خارج از محدوده مجاز است.
        /// </summary>
        public static string MsgImageDimensionIsInvalid {
            get {
                return ResourceManager.GetString("MsgImageDimensionIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حجم تصویر بیشتر از حداکثر مقدار مجاز است.
        /// </summary>
        public static string MsgImageSizeIsLarge {
            get {
                return ResourceManager.GetString("MsgImageSizeIsLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورود انجام نشد، اطلاعات ورودی خود را بررسی کنید..
        /// </summary>
        public static string MsgLoginFailed {
            get {
                return ResourceManager.GetString("MsgLoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلمه حداکثر پنجاه حرف است.
        /// </summary>
        public static string MsgMaxPasswordLengthIs50 {
            get {
                return ResourceManager.GetString("MsgMaxPasswordLengthIs50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلمه عبور حداقل چهار حرف است.
        /// </summary>
        public static string MsgMinPasswordLengthIs4 {
            get {
                return ResourceManager.GetString("MsgMinPasswordLengthIs4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلمه عبور و تکرار آن یکسان نیست.
        /// </summary>
        public static string MsgPasswordConfirmMismatch {
            get {
                return ResourceManager.GetString("MsgPasswordConfirmMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلمه عبور اشتباه است.
        /// </summary>
        public static string MsgPasswordIsIncorect {
            get {
                return ResourceManager.GetString("MsgPasswordIsIncorect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا یک فایل را انتخاب کنید.
        /// </summary>
        public static string MsgPleaseSelectOneFile {
            get {
                return ResourceManager.GetString("MsgPleaseSelectOneFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا یک فایل تصویر jpg را انتخاب کنید.
        /// </summary>
        public static string MsgPleaseSelectOneJpgImage {
            get {
                return ResourceManager.GetString("MsgPleaseSelectOneJpgImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ارسال شده بعد از 48 ساعت منقضی خواهد شد..
        /// </summary>
        public static string MsgSentCodeWillBeExpired {
            get {
                return ResourceManager.GetString("MsgSentCodeWillBeExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زبان مبدا و مقصد باید متفاوت باشد.
        /// </summary>
        public static string MsgSourceAndTargetLanguagesShouldBeDifferent {
            get {
                return ResourceManager.GetString("MsgSourceAndTargetLanguagesShouldBeDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طول {0} حداقل {1} و حداکثر {2} کاراکتر است.
        /// </summary>
        public static string MsgStringLengthRange {
            get {
                return ResourceManager.GetString("MsgStringLengthRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد تایید عضویت به آدرس ایمیل شما ارسال شد.
        /// </summary>
        public static string MsgVerficaionCodeSent {
            get {
                return ResourceManager.GetString("MsgVerficaionCodeSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پذیرش شرایط استفاده الزامی است.
        /// </summary>
        public static string MsgYouShouldAcceptLicenceTerms {
            get {
                return ResourceManager.GetString("MsgYouShouldAcceptLicenceTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلمه عبور جدید.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تکرار کلمه عبور.
        /// </summary>
        public static string NewPasswordConfirm {
            get {
                return ResourceManager.GetString("NewPasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تایید نشده.
        /// </summary>
        public static string NotConfirmed {
            get {
                return ResourceManager.GetString("NotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای «{0}» یک دیدگاه ثبت کرد.
        /// </summary>
        public static string NotificationMessage_WriteComment {
            get {
                return ResourceManager.GetString("NotificationMessage_WriteComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای شما یک پیام خصوصی ارسال کرده است.
        /// </summary>
        public static string NotificationMessage_WriteMessage {
            get {
                return ResourceManager.GetString("NotificationMessage_WriteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشخص نشده.
        /// </summary>
        public static string NotSpecified {
            get {
                return ResourceManager.GetString("NotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشاهده.
        /// </summary>
        public static string Observation {
            get {
                return ResourceManager.GetString("Observation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام سازمان.
        /// </summary>
        public static string OrganizationName {
            get {
                return ResourceManager.GetString("OrganizationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلمه عبور.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور و تکرار رمز عبور یکسان نیست..
        /// </summary>
        public static string PasswordAndConfirmPasswordDoNotMatch {
            get {
                return ResourceManager.GetString("PasswordAndConfirmPasswordDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلمه عبور و تکرار آن یکسان نیست.
        /// </summary>
        public static string PasswordAndPasswordConfirmMismatch {
            get {
                return ResourceManager.GetString("PasswordAndPasswordConfirmMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغییر کلمه عبور.
        /// </summary>
        public static string PasswordChange {
            get {
                return ResourceManager.GetString("PasswordChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تکرار کلمه عبور.
        /// </summary>
        public static string PasswordConfirm {
            get {
                return ResourceManager.GetString("PasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات شخصی.
        /// </summary>
        public static string PersonalInfo {
            get {
                return ResourceManager.GetString("PersonalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مطالب پربازدید.
        /// </summary>
        public static string PopularContent {
            get {
                return ResourceManager.GetString("PopularContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ابعاد تصویر بیشتر از حدکثر مجاز است. ابعاد تصویر ارسالی باید حداکثر 600 در 600 پیکسل باشد..
        /// </summary>
        public static string ProfileImageDimensionsIsTooLarge {
            get {
                return ResourceManager.GetString("ProfileImageDimensionsIsTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ابعاد تصویر خیلی کوچک است. ابعاد تصویر ارسالی باید حداقل 100 پیکسل در 100 پیکسل باشد..
        /// </summary>
        public static string ProfileImageDimensionsIsTooSmall {
            get {
                return ResourceManager.GetString("ProfileImageDimensionsIsTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اندازه تصویر انتخاب شده بیشتر از حداکثر مقدار مجاز است.
        /// </summary>
        public static string ProfileImageSizeIsTooLarge {
            get {
                return ResourceManager.GetString("ProfileImageSizeIsTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تصویر پروفایل.
        /// </summary>
        public static string ProfilePicture {
            get {
                return ResourceManager.GetString("ProfilePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منتشر شود.
        /// </summary>
        public static string Published {
            get {
                return ResourceManager.GetString("Published", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت کاربر.
        /// </summary>
        public static string RegisterUser {
            get {
                return ResourceManager.GetString("RegisterUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ عضویت.
        /// </summary>
        public static string RegistrationDate {
            get {
                return ResourceManager.GetString("RegistrationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فعلا امکان ثبت نام وجود ندارد. این امکان به زودی فعال می شود..
        /// </summary>
        public static string RegistrationIsDisabledNow {
            get {
                return ResourceManager.GetString("RegistrationIsDisabledNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرا به خاطر بسپار.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الزامی.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازگشت.
        /// </summary>
        public static string Return {
            get {
                return ResourceManager.GetString("Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شنبه.
        /// </summary>
        public static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ذخیره.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ذخیره شد.
        /// </summary>
        public static string Saved {
            get {
                return ResourceManager.GetString("Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال کد تایید.
        /// </summary>
        public static string SendConfirmCode {
            get {
                return ResourceManager.GetString("SendConfirmCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جنسیت.
        /// </summary>
        public static string Sexuality {
            get {
                return ResourceManager.GetString("Sexuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چکیده یک خطی.
        /// </summary>
        public static string ShortAbstract {
            get {
                return ResourceManager.GetString("ShortAbstract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورود.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من را عضو کن.
        /// </summary>
        public static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خلاصه متن اصلی.
        /// </summary>
        public static string SourceContentSummary {
            get {
                return ResourceManager.GetString("SourceContentSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زبان منبع.
        /// </summary>
        public static string SourceLanguage {
            get {
                return ResourceManager.GetString("SourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان منبع.
        /// </summary>
        public static string SourceTitle {
            get {
                return ResourceManager.GetString("SourceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس اینترنتی منبع.
        /// </summary>
        public static string SourceWebAddress {
            get {
                return ResourceManager.GetString("SourceWebAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سال شروع.
        /// </summary>
        public static string StartYear {
            get {
                return ResourceManager.GetString("StartYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در یک نگاه.
        /// </summary>
        public static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} باید حداقل {2} کاراکتر باشد..
        /// </summary>
        public static string StringLengthLimit {
            get {
                return ResourceManager.GetString("StringLengthLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یکشنبه.
        /// </summary>
        public static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پنجشنبه.
        /// </summary>
        public static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تا کنون.
        /// </summary>
        public static string ToNow {
            get {
                return ResourceManager.GetString("ToNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نویسندگان برتر.
        /// </summary>
        public static string TopAuthors {
            get {
                return ResourceManager.GetString("TopAuthors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ترجمه.
        /// </summary>
        public static string Translation {
            get {
                return ResourceManager.GetString("Translation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متن ترجمه.
        /// </summary>
        public static string TranslationContent {
            get {
                return ResourceManager.GetString("TranslationContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زبان ترجمه.
        /// </summary>
        public static string TranslationLanguage {
            get {
                return ResourceManager.GetString("TranslationLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سه شنبه.
        /// </summary>
        public static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس توییتر.
        /// </summary>
        public static string TwitterUrl {
            get {
                return ResourceManager.GetString("TwitterUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رشته.
        /// </summary>
        public static string UniversityFieldName {
            get {
                return ResourceManager.GetString("UniversityFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس اینترنتی.
        /// </summary>
        public static string Url {
            get {
                return ResourceManager.GetString("Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فعال‌سازی حساب کاربری.
        /// </summary>
        public static string UserAccountActivation {
            get {
                return ResourceManager.GetString("UserAccountActivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس وب سایت.
        /// </summary>
        public static string WebSiteUrl {
            get {
                return ResourceManager.GetString("WebSiteUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چهارشنبه.
        /// </summary>
        public static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زن.
        /// </summary>
        public static string Woman {
            get {
                return ResourceManager.GetString("Woman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نگارش.
        /// </summary>
        public static string Writing {
            get {
                return ResourceManager.GetString("Writing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب کاربری شما فعال نشده است. لطفا به پست الکترونیک خود مراجعه کنید و روی لینک فعال سازی کلیک کنید..
        /// </summary>
        public static string YourAccountHasNotActivated {
            get {
                return ResourceManager.GetString("YourAccountHasNotActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب کاربری شما غیرفعال شده است..
        /// </summary>
        public static string YourAccountIsLocked {
            get {
                return ResourceManager.GetString("YourAccountIsLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زیگماوب.
        /// </summary>
        public static string ZigmaWeb {
            get {
                return ResourceManager.GetString("ZigmaWeb", resourceCulture);
            }
        }
    }
}
